/**
 * Danh mục mã lỗi và HTTP status. Nguồn duy nhất: docs/api/error-codes.md.
 * Thêm mã mới ở file đó trước (Hồng Anh), rồi chép sang đây; Triển cập nhật openapi.yaml.
 */
export const ERROR_HTTP_STATUS = {
  VALIDATION_ERROR: 400,
  UNAUTHENTICATED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INVALID_CREDENTIALS: 401,
  ACCOUNT_LOCKED: 403,
  ACCOUNT_TEMPORARILY_LOCKED: 429,
  ACTIVATION_REQUIRED: 409,
  PHONE_DUPLICATED: 409,
  EMAIL_DUPLICATED: 409,
  TOKEN_EXPIRED: 400,
  INVALID_FILE: 422,
  PENDING_ORDER_EXISTS: 409,
  CASH_AMOUNT_MISMATCH: 422,
  NO_ACTIVE_SUBSCRIPTION: 422,
  SUBSCRIPTION_EXPIRED: 422,
  SUBSCRIPTION_FROZEN: 422,
  SUBSCRIPTION_NOT_ACTIVE: 409,
  SUBSCRIPTION_NOT_FROZEN: 409,
  ALREADY_CHECKED_IN: 409,
  INVALID_QR: 422,
  FREEZE_BLOCKED_BY_APPOINTMENTS: 409,
  SCHEDULE_CONFLICT: 409,
  STALE_VERSION: 409,
  NO_SESSIONS_AVAILABLE: 422,
  OUTSIDE_SUBSCRIPTION_PERIOD: 422,
  SESSION_NOT_ENDED: 422,
  NO_CLASS_BENEFIT: 422,
  CLASS_FULL: 409,
  CANCELLATION_WINDOW_PASSED: 422,
  ROLE_CHANGE_NOT_ALLOWED: 422,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
} as const;

export type ErrorCode = keyof typeof ERROR_HTTP_STATUS;
